### ISSUE TITLE
Erreur sur l'installation du plugin

### ISSUE THREAD

**Issue by flemzord** [WordPressUtilities/wpudisplayinstagram#1]
Salut, 

J'ai essayer d'installer le plugin, et wordpress ma donné l'erreur suivante : 

Fatal error: Call to a member function register_post_types() on null in /wp-content/plugins/wpudisplayinstagram/wpudisplayinstagram.php on line 533

Cordialement, 
Maxence

**Comment by Darklg** [comment]
Oh, désolé !

Je corrige de suite.

Attention, pour info, ce plugin est dépendant de https://github.com/WordPressUtilities/wpuoptions

**Comment by Darklg** [comment]
Voilà ! Et en prime j'ai rajouté un widget :')
